services:
  db:
    image: postgres:12.3-alpine
    env_file: .env
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - default
  web:
    build: .
    env_file: .env
    image: web
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    ports:
      - 3000:3000
    volumes:
      - .:/opt/app/
      - bundle_cache:/bundle
    depends_on:
      - db
    networks:
      default:

volumes:
  bundle_cache:
  db:

networks:
  default:
    driver: bridge
