version: 2.0
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/ruby:3.0.0-node-browsers
      environments:
        RAILS_ENV: test
        POSTGRES_USER: ubuntu
        POSTGRES_DB: dns_api_test

    - image: circleci/postgres:12-alpine-ram
      environments:
        POSTGRES_USER: ubuntu
        POSTGRES_DB: dns_api_test
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run:
          name: Setup database
          command: bundle exec rake db:create db:schema:load

      - run:
          name: Setup PostgreSQL client
          command: sudo apt-get --allow-releaseinfo-change update && sudo apt install postgresql-client

      - run:
          name: Run tests
          command: bundle exec rspec --color --require spec_helper spec --format progress
